# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_hello',
                'doc_host': 'https://klausreus.github.io',
                'git_url': 'https://github.com/klausreus/nbdev_hello',
                'lib_path': 'nbdev_hello'},
  'syms': { 'nbdev_hello.process_images': { 'nbdev_hello.process_images.add_2': ('core.html#add_2', 'nbdev_hello/process_images.py'),
                                            'nbdev_hello.process_images.say_hello': ( 'core.html#say_hello',
                                                                                      'nbdev_hello/process_images.py')}}}
