# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['add_2', 'say_hello']

# %% ../nbs/00_core.ipynb 3
def add_2(x):
    return x+2

# %% ../nbs/00_core.ipynb 4
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
